### PR TITLE
Propose When if we can When Getting VID Dispersal Info

### LINKED ISSUE #2207: [BUG FIX] - Fix Failure To Propose because of no VID data
### What is this task and why do we need to work on it?

We are getting the log "Wasn't able to publish proposal" often in test net.  This would happen when we form a QC but don't yet have the payload commitment from the VID task and therefore cannot propose.  This would be fine but when we do get the data we need we don't actually create another proposal.

### What work will need to be done to complete this task?

- [ ] Add Logging when this specific situation occurs
- [ ] Fix the bug by trying to propose when we get the VID data
- [ ] Confirm that it fixes the bug by seeing the logging we added hit, and then a decided happen for that same view.

### Are there any other details to include?

_No response_

### What are the acceptance criteria to close this issue?

The last bullet point above:  Confirm that it fixes the bug by seeing the logging we added hit, and then a decided happen for that same view.

### Branch work will be merged to (if not the default branch)

_No response_

### PR DESCRIPTION
**Pull request by bfish713**
Closes #2207 

### This PR: 

Fixes a bug where we can't propose because VID disperse is still pending, but then we don't try to propose after it completes.  This adds the logic to propose if we can after the disperse compeltes

### Key places to review: 

The added code in consensus.rs

### How to test this PR: 

I added a short `async_sleep` for 300ms immediately before sending the `SendPayloadCommitmentAndMetadata` event.  This was enough timing disruption to hit the bug in almost every view.  With my fix and warn logs on you should see "Cannot propose because we don't have the VID payload commitment and metadata" but the view won't timeout because the proposer succeeds later when it gets the info it needs

### CODE REVIEW

**Comment by rob-maron** [comment]
A question for my understanding: is there a reason we don't just remove the other call to `propose_if_able` and use this one instead? (If we're saying we can't propose until the VID disperse is done). Or is this a situation where it's now basically `min(vid disperse, payload commitment)`?

**Comment by bfish713** [comment]
> A question for my understanding: is there a reason we don't just remove the other call to `propose_if_able` and use this one instead? (If we're saying we can't propose until the VID disperse is done). Or is this a situation where it's now basically `min(vid disperse, other criterion)`?

It's actually that we can't propose unless all three of the following conditions are met: 

1. We saw the last proposal (or formed a timeout cert)
2. We collected enough votes and formed a QC on that proposal (or formed a timeout cert)
3. We have the VID disperse information (payload commit and metadata).

These 3 things can come in any order so we might propose during the events for any of the 3.

**Comment by rob-maron** [comment]
> > A question for my understanding: is there a reason we don't just remove the other call to `propose_if_able` and use this one instead? (If we're saying we can't propose until the VID disperse is done). Or is this a situation where it's now basically `min(vid disperse, other criterion)`?
> 
> It's actually that we can't propose unless all three of the following conditions are met:
> 
> 1. We saw the last proposal (or formed a timeout cert)
> 2. We collected enough votes and formed a QC on that proposal (or formed a timeout cert)
> 3. We have the VID disperse information (payload commit and metadata).
> 
> These 3 things can come in any order so we might propose during the events for any of the 3.

Got it, thanks !

**Review by rob-maron — APPROVED** [review]
Looks good !

**Review by shenkeyao — APPROVED** [review]
Looks good!

**Pull request merged**
