### PR TITLE
Fix lints

### PR DESCRIPTION
**Pull request by shenkeyao**
- Fixes lints on the `run_view_refactor` branch.
- Also includes some other fixes. Relevant commits:
  - Fix view sync cert validation: https://github.com/EspressoSystems/HotShot/commit/591f283348506b4854df2d1e629726b10640b221
  - Fix harness.rs and view sync trigger: https://github.com/EspressoSystems/HotShot/commit/bd27ccaea4fab55ba2e28309fc8ab3a990644c30
  - Update inject_consensus_info to return nothing, remove ConsensusInfo and run_background_receive: https://github.com/EspressoSystems/HotShot/commit/06292005f820defe57e71cfd1e98672d6d999236
  - Fix generics on type alias, fix count logging for examples: https://github.com/EspressoSystems/HotShot/commit/59b346ad3ddc9cdca752363d390d3fe919d86783

Related issue: https://github.com/EspressoSystems/HotShot/issues/1418.

### CODE REVIEW

**Review by DieracDelta — APPROVED** [review]
This looks really great!!

**Comment by bfish713** [comment]
I noticed that when I run the tests for this branch the logging shows no transactions being included in the block.  Doesn't appear to happen on the `run_view_refactor` branch

**Comment by shenkeyao** [comment]
> I noticed that when I run the tests for this branch the logging shows no transactions being included in the block. Doesn't appear to happen on the `run_view_refactor` branch

Good catch! Investigating now...

**Comment by shenkeyao** [comment]
> > I noticed that when I run the tests for this branch the logging shows no transactions being included in the block. Doesn't appear to happen on the `run_view_refactor` branch
> 
> Good catch! Investigating now...

@bfish713 Ahh I found it! I accidentally removed `TransactionsRecv` from the event filter of the DA task. Will send an update soon.

**Review by bfish713 — APPROVED** [review]

**Pull request merged**
