### PR TITLE
[VALIDATED_STATE] - Add state to header and remove metadata getter

### PR DESCRIPTION
**Pull request by shenkeyao**
Closes https://github.com/EspressoSystems/HotShot/issues/2463.

### This PR: 
* Adds the parent state to the `BlockHeader` construction.
* Removes the metadata getter function from the `State` trait.

### Key places to review: 
* crates/testing/src/block_types.rs

### CODE REVIEW

**Review by jbearer — APPROVED** [review]
I think this is sufficient.

I did realize that since `Header::new` gets the parent state, not the new state, we will end up calculating the new state twice in the leader node. `Header::new` will effectively have to duplicate some of the `validate_and_apply` logic in order to include the new state commitment in the header. Then the consensus task within the leader node will end up doing the full `validate_and_apply` to check that the state commitment in the proposed header is consistent with applying that proposal to the parent state. This could maybe be optimized by passing the computed state from the leader task to the replica task, but probably not important for now

**Comment by shenkeyao** [comment]
> I did realize that since `Header::new` gets the parent state, not the new state, we will end up calculating the new state twice in the leader node. `Header::new` will effectively have to duplicate some of the `validate_and_apply` logic in order to include the new state commitment in the header. Then the consensus task within the leader node will end up doing the full `validate_and_apply` to check that the state commitment in the proposed header is consistent with applying that proposal to the parent state. This could maybe be optimized by passing the computed state from the leader task to the replica task, but probably not important for now

Makes sense! I made an issue for this: https://github.com/EspressoSystems/HotShot/issues/2465. I labeled it as low priority and could work on it after the major tasks for the validated state are done.

**Comment by tbro** [comment]
I noticed you removed the `fn metadata()`. Should the associated type `Metadata` on the `impl State for TestState` in `state_types.rs` (line 63) also be removed?

**Comment by shenkeyao** [comment]
> I noticed you removed the `fn metadata()`. Should the associated type `Metadata` on the `State` trait and implementation for `TestState ` also be removed?

I think the `Metadata` type is still useful for the sequencer to pass in the app-specific data. It’s an unknown type for HotShot so we need it to be an associated type. We could remove the `metadata` function because we don’t need to retrieve it in HotShot.

**Comment by jbearer** [comment]
Wait but the `Metadata` type is no longer used anywhere in the `State` trait. Wouldn't we just refer to `Header::Metadata` when we need to name this type elsewhere in HotShot?

**Review by jbearer — APPROVED** [review]

**Pull request merged**
