### PR TITLE
Fix the return value of builder transaction status API

### PR DESCRIPTION
**Pull request by dailinsubjam**
### This PR: 
- fix the return value of txn stat api

### CODE REVIEW

**Comment by shenkeyao** [comment]
Having the same question as @ss-es about the change. :thinking:

**Comment by dailinsubjam** [comment]
@ss-es @shenkeyao Original code will return  `Ok(transaction_commit)`, after the fix it will return `Result(TransactionStatus, BuildError)`. Or am I missing anything?

**Comment by ss-es** [comment]
Oh sorry, I see - yes you're completely right! It used to return `Result<tx.commit(), Error::TxnStat>` but now it returns something like `Result<state.txn_status, Error::TxnStat>`

ignore my comment -- it looks good to me!

**Comment by shenkeyao** [comment]
> @ss-es @shenkeyao Original code will return `Ok(transaction_commit)`, after the fix it will return `Result(TransactionStatus, BuildError)`. Or am I missing anything?

Totally makes sense. 😃

**Review by shenkeyao — APPROVED** [review]

**Pull request merged**
