### PR TITLE
[VALIDATED_STATE] - Make `Committable` a supertrait of `BlockHeader` and merge changes in `develop`

### PR DESCRIPTION
**Pull request by shenkeyao**
Closes https://github.com/EspressoSystems/HotShot/issues/2167.

### This PR: 
* Makes `Committable` a supertrait of `BlockHeader`.
  * Adds `:Committable` to `BlockHeader`.
  * Implements `Committable` for `TestBlockHeader`.
  * Updates commitment tags.
* Merges `develop` into `main.

### CODE REVIEW

**Review by jbearer — DISMISSED** [review]
LGTM

**Comment by jbearer** [comment]
Oh can we merge this into `main`? Or merge `develop` into `main` right after merging this into `develop`? This is a blocker for the downstream integration

**Review by jbearer — APPROVED** [review]
This also brings in Artemii's reorganization of test code. That's a good thing IMO, just making sure that was intended

**Comment by shenkeyao** [comment]
> This also brings in Artemii's reorganization of test code. That's a good thing IMO, just making sure that was intended

@jbearer Good catch! Since this code was originally based on `develop`, merging it into main is essentially merging `develop` into `main. Let me double-check with the team--we discussed last week about getting rid of `develop`.

**Comment by jbearer** [comment]
If this is all that's on develop right now, merging it into main should be fine

**Review by jbearer — APPROVED** [review]

**Review by rob-maron — APPROVED** [review]

**Pull request merged**
