### PR TITLE
Imrovements for WebServerNetwork

### LINKED ISSUE #2206: [FIX_CI] - Fix web_server_network test
### What is this task and why do we need to work on it?

`web_server_network` test sporadically fails in CI:
```
Message:  TEST FAILED! Results: [("Test Overall Safety Task", NotEnoughDecides { expected: 35, got: 0 })]
Location: /opt/actions-runner/_work/HotShot/HotShot/crates/testing/src/test_runner.rs:177
```
with following error making appearance in the logs:
```
Failed to send message from network task: WebServer { source: ClientError }
```

### What work will need to be done to complete this task?

Locate and fix the cause of `web_server_network` failing

### Are there any other details to include?

_No response_

### What are the acceptance criteria to close this issue?

`web_server_network` passes consistently

### Branch work will be merged to (if not the default branch)

_No response_

### PR DESCRIPTION
**Pull request by QuentinI**
Closes #2206
(which was just closed in #2230, this is mostly improvements on top of that)

### This PR:
- Logs an error when webserver task finishes, which isn't something it's supposed to do
  The actual reason for #2206 was that we've been picking ports from the entire u16 value space, which ran into system ports eventually and server failed to start. This issue was fixed by @rob-maron in #2230, this PR just adds logging to appropriate places so when web server fails it doesn't do that silently.
- When creating a `WebServerNetwork`, allows to wait for the web server to come online
  I suspected it as a cause for #2206, but it ultimately wasn't. I think it still makes sense, so I didn't throw the code out.

### This PR does not: 
Do anything else

### Key places to review: 
`crates/hotshot/src/traits/networking/web_server_network.rs`:
- `WebServerNetwork::create`
- `WebServerNetwork::generator`

### CODE REVIEW

**Comment by QuentinI** [comment]
Drafted since it seems like I have broken some tests

**Comment by rob-maron** [comment]
> Drafted since it seems like I have broken some tests

If you're running into the combined network failure, those were fixed in a recent commit to `main`. So depending on your base you might want to `git merge origin/main` 😄

**Comment by rob-maron** [comment]
🤔 Hmm, okay. For the combined network tests, they throw a bunch of events at the webserver telling it to shut down, start up, pause, resume, etc.

Since the combined network is both the libp2p and webserver networks (and will work if it can't connect to the webserver network) I think the panic when we can't connect is causing the issue.

**Comment by QuentinI** [comment]
There's something really weird going on with this branch. I'm closing this for now, since whatever it is it doesn't cause any issues for us on main, but I feel like something somewhere doesn't behave like it should, so I'll continue to investigate in my spare time.

**Pull request closed without merging**
