### PR TITLE
[Tech Debt] Move `task-impls` to hotshot

### LINKED ISSUE #2294: [Tech Debt] - Move `task-impls` crate to `hotshot`
### What is this task and why do we need to work on it?

As far as I understand,`task-impls` is a separate crate for historical reasons. There's no reason it can't be demoted to a submodule, which would also allow removing `ConsensusApi` trait (currently such removal runs into dependency cycle between `hotshot` and `task-impls`).

### What work will need to be done to complete this task?

`task-impls` crate removed, code moved to `hotshot` crate.

### Are there any other details to include?

_No response_

### What are the acceptance criteria to close this issue?

`task-impls` doesn't exist as a separate crate.

### Branch work will be merged to (if not the default branch)

_No response_

### PR DESCRIPTION
**Pull request by QuentinI**
Closes #2294

### This PR: 
Demotes `task-impls` from a crate to a part of `hotshot`

### This PR does not: 
include any additional refactorings

### Key places to review: 
`hotshot::tasks` submodule, which is where `task-impls` was moved.

### CODE REVIEW

**Review by shenkeyao — APPROVED** [review]
LGTM!

**Comment by QuentinI** [comment]
@shenkeyao can you re-approve please? Had to merge main since GitHub complained about conflicts

**Review by shenkeyao — DISMISSED** [review]

**Comment by bfish713** [comment]
Since this already has some conflicts can we hold off on this until: https://github.com/EspressoSystems/HotShot/pull/2500 is merged since it changes so much in task_impls

**Comment by bfish713** [comment]
This is unblocked now

**Pull request closed without merging**
